default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  server: localhost
  database: sentran_development
  username: ubuntu
  password: rails
  host: localhost

production:
  <<: *default
